name: reddit_posts
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^7.7.1
  intl: ^0.18.1
  provider: ^6.0.5
  # webview_flutter: ^4.0.7
  # url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  freezed: ^2.4.2
  auto_route_generator: ^7.2.0


flutter:
  uses-material-design: true

